services:
  webapi:
    container_name: dev-webapi
    build:
      context: ../webapi
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - NODE_ENV=development
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
    ports:
      - "5000:5000" # .NETのデフォルトポート
      - "5001:5001" # .NETのHTTPSポート

  webapp:
    container_name: dev-webapp
    build:
      context: ../webapp
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173" # Vite のデフォルトポート
    stdin_open: true
    tty: true
    depends_on:
      - webapi

